### ISSUE TITLE
Complete Checkout Flow

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/boilerplate#5]
- [ ] Setup and Integrate Datatrans and Invoice Payment Providers
- [ ] Setup Order Confirmation E-Mail's
- [x] Add orders and order details pages to profile

**Comment by pozylon** [comment]
https://github.com/unchainedshop/unchained/pull/158

**Comment by schmidsi** [comment]
OrderList information:
- Order date (Order is Confirmed)
- Total cost
- Adresses: Delivery/Invoice (short)
- Shipping Type

OrderDetail:
- List of a ordered items with cost
- Full adresses
- VAT calculations
